apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cofry

resources:
  - namespace.yaml
  - secret-db.yaml
  - configmap-backend.yaml
  - pvc-db.yaml
  - statefulset-db.yaml
  - deployment-backend.yaml
  - deployment-frontend.yaml
  - ingress.yaml
