# ==============================================================
# Secret: credenciais do banco de dados (base64 encoded)
# Para gerar: echo -n "valor" | base64
#
# postgres     → cG9zdGdyZXM=
# jala.0725   → amFsYS4wNzI1
# ==============================================================
apiVersion: v1
kind: Secret
metadata:
  name: cofry-db-secret
  namespace: cofry
type: Opaque
data:
  # echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n "jala.0725" | base64
  POSTGRES_PASSWORD: amFsYS4wNzI1
  # echo -n "postgres" | base64
  POSTGRES_DB: cG9zdGdyZXM=
